### PR TITLE
Delete in Filebrowser top-bar

### PR DESCRIPTION
**Pull request by RichardMcCarty1**

### CODE REVIEW

**Comment by bowring** [comment]
All seems well - might as well merge?

**Comment by RichardMcCarty1** [comment]
Yeah, although I do have plans for some more Filebrowser updates, primarily the dynamic context-menu for right click actions once I can get it to work appropriately.

**Comment by bowring** [comment]
Works great!

**Comment by bowring** [comment]
now managespots page produces:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:8080/squid_servlet-1.0.0/spotspull. (Reason: header ‘access-control-allow-origin’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).

**Comment by RichardMcCarty1** [comment]
And thats within a CORS browser correct? I might just try to tackle the
root cause of the CORS issues so we don't have to worry about the browsers
and everything for the rest of development.

**Comment by bowring** [comment]
I deleted my comment from here as it was wrong repo.  Anyway, managespots loads in Chrome but not Firefox now both with CORS off.

**Comment by RichardMcCarty1** [comment]
Alright, I'm wrapping up the ManageSpots functionalities currently so when
those are finished I'll take a look at resolving the CORS issues once and
for all.

**Comment by bowring** [comment]
problem - double click a squid file and it goes to download it

**Comment by RichardMcCarty1** [comment]
Just pushed up a fix for it.

**Comment by bowring** [comment]
same issue for .xml;

**Comment by bowring** [comment]
good start ... double click still does download instead of load for xml and zip

zip does not provide loading menu either

**Comment by bowring** [comment]
additionally - the floating menu item does not always appear for opening files

**Comment by bowring** [comment]
the issue occurs when the filebrowser is resized - the floating menus disappear

**Comment by RichardMcCarty1** [comment]
That's strange, I tested it on mine with the SamplePrawnFiles and they opened fine. I'll do some more digging.

**Comment by bowring** [comment]
also, when the menu is present, an empty menu appears. on folders and others not used

I note that if I scroll the menus remain stationary

**Comment by RichardMcCarty1** [comment]
Just pushed up a change to temporarily disable the context menu. I wasn't ever really happy with its implementation and it seems it hasn't quite grown as the rest of the Filebrowser has. I'll add it to my list and look into a better solution.

In reference to the .zip and .xml files, they seem to be running for me locally. I'd go ahead and pull down the context menu change as an opportunity to rebuild the program. They were also accompanied by a change for SquidinkWebServices so maybe rebuild that one as well.

**Comment by bowring** [comment]
Looking good.  Here's a thought - if we can't customize the icons, maybe we should get rid of them to provide more space?

**Review by bowring — APPROVED** [review]
good work!

**Pull request merged**
